### ISSUE TITLE
Completion fails with python-lsp-server/WebSocket

### ISSUE THREAD

**Issue by avivbrg** [mkslanc/ace-linters#63] opened 2023-05-31 13:38 UTC
I'm trying to connect with [python-lsp-server](https://github.com/python-lsp/python-lsp-server) and facing a few issues:

1. Completion doesn't work. It seems `toCompletions()` expects a list of `CompletionService` but gets the actual completion response from the server (once I worked around this completion worked). This most likely broke in v0.9.0

2. I'm getting a lot of exceptions in `fromSignatureHelp()`: 
`ace-language-client.js:19408 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'label')`
`    at ace-language-client.js:19408:40`
`    at Array.map (<anonymous>)`
`    at fromSignatureHelp (ace-language-client.js:19404:33)`
`    at ace-language-client.js:19836:141`
`    at signatureHelpCallback (ace-language-client.js:20548:25)`
`    at MessageControllerWS.callbackFunction (ace-language-client.js:20515:13)`
`    at MessageControllerWS.emit (ace-language-client.js:2504:5)`
`    at ace-language-client.js:20519:18`

 3. Not a bug, but I couldn't figure out how to enable live completion with websocket/lsp server (live completion does work with the built-in completion) - is this supported?
 
 4. Could you please pass the `options` parameter to `workspace/didChangeConfiguration:settings` (or add a new parameter) to enable configuring the server?

Cheers
Aviv

**Comment by mkslanc** [comment] 2023-06-02 09:50
Thank you for reaching out, @avivbrg! The first three points should be fixed by [this PR](https://github.com/mkslanc/ace-linters/pull/64). I am planning to provide a feature for the fourth point and release new version today.

**Comment by avivbrg** [comment] 2023-06-03 10:02
Thanks for the super quick fix!
Live completion work much better now :-)

I've found three more issues:
1. While the completion results are showing consistently now, the selected completion is not always inserted into the document. Looking into the completion results received from the server it seems that if the completion has a `snippet` field (and hence the `value` field is `""`) it will fail to insert (completions without a `snippet` field are fine). Snippet support is enabled for the editor.

2. The hover tooltip does not match the editor theme (colours and fonts, see attached screen capture), is there a setting I'm missing?
![Screenshot 2023-06-03 at 7 36 03 pm](https://github.com/mkslanc/ace-linters/assets/33679460/eb399c43-c7cd-4f37-9ea3-73667b17ae72)

3. Live completion works, but does not tigger after `.` - I'm using the following code to enable it:
`    editor.commands.on("afterExec", function (e) {`
`     if (e.command.name == "insertstring" && /^[\w.]$/.test(e.args)) {`
`         editor.execCommand("startAutocomplete");`
`      }`
`    });`
Is this the recommended approach?

**Comment by mkslanc** [comment] 2023-06-03 10:54
1. Could you bring reproduction steps/example? I couldn't reproduce it.
2. I think this would be solved when I migrate to introduced in https://github.com/ajaxorg/ace/releases/tag/v1.18.0 HoverTooltip
3. If you are using ace version after [v1.21.0](https://github.com/ajaxorg/ace/releases/tag/v1.21.0) you could just do something like that 
```javascript
let completer = editor.completers.find((el) => el.id === "lspCompleters");
        completer.triggerCharacters = ["."]
```

**Comment by mkslanc** [comment] 2023-06-03 18:25
@avivbrg The new version of ace-linters (v0.11.1) supports setting configurations and resolves other client-related bugs. You can find the updated package [here](https://www.npmjs.com/package/ace-linters/v/0.11.1). Additionally, you may want to check out the [new example](https://github.com/mkslanc/ace-linters/blob/main/packages/demo/websockets-pylsp/client.ts) that demonstrates how to provide options to pylsp.

**Comment by avivbrg** [comment] 2023-06-04 03:42
Thanks @mkslanc !

I've reproduced it with the update package:

server:
```
pip install python-lsp-server python-lsp-ruff
pylsp --ws --port 3000
```

html:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>ACE Autocompletion demo</title>
  <style type="text/css" media="screen">
    body {
        overflow: hidden;
    }
    
    #editor { 
        margin: 0;
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
    }
  </style>
</head>
<body>

<pre id="editor"></pre>

<script src="/ace-builds/src-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
<script src="/ace-builds/src-noconflict/ext-language_tools.js" type="text/javascript" charset="utf-8"></script>></script>
<script src="/ace-linters/build/ace-linters.js" type="text/javascript" charset="utf-8"></script>
<script src="/ace-linters/build/ace-language-client.js" type="text/javascript" charset="utf-8"></script>

<script>
    
    var editor = ace.edit("editor", {
        enableBasicAutocompletion: true,
        enableLiveAutocompletion: true,
        enableSnippets: true,
        mode: "ace/mode/python",
        theme: "ace/theme/monokai"
    });

    const webSocket = new WebSocket("ws://localhost:3000/");
    var provider = AceLanguageClient.for(webSocket)
    provider.setGlobalOptions("", {
      "pylsp": {
          "plugins": {
              "ruff": {
                "enabled": true,
              },
              "preload": {
                "enabled": true,
                "modules": ["os", "sys"]
              },

              "jedi_completion": {
                "enabled": true,
                "include_params": true,
              },
              "jedi_hover": {
                "enabled": true,
              },
              "jedi_signature_help": {
                "enabled": true,
              },
          }
        }
    })
    provider.registerEditor(editor);

    
    editor.commands.on("afterExec", function (e) {
      if (e.command.name == "insertstring" && /^[\w.]$/.test(e.args)) {
          editor.execCommand("startAutocomplete");
      }
    });

    //let completer = editor.completers.find((el) => el.id === "lspCompleters");
    //completer.triggerCharacters = ["."]

</script>

</body>
</html>
```

Successful completion: `sys.exit`, completion result from the server:
![Screenshot 2023-06-04 at 1 27 13 pm](https://github.com/mkslanc/ace-linters/assets/33679460/c5b7c4ba-19db-49f8-a33f-add05344c6af)

Failed completion: `sys.call_tracing`, completion result from the server:
![Screenshot 2023-06-04 at 1 27 57 pm](https://github.com/mkslanc/ace-linters/assets/33679460/18f76ae6-61b0-458a-aa64-77728bd90a6e)


Regarding #3: it works, but not as reliably as the previous solution (e.g. `psutil.` will trigger a dropdown list, `sys.` will not)

**Comment by mkslanc** [comment] 2023-06-04 11:50
@avivbrg Published new version - completions snippets should be fixed

**Comment by avivbrg** [comment] 2023-06-04 11:56
Awesome, thanks!

**Closed** 2023-06-04 12:03 UTC
Labels: bug, enhancement
